
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import { Providers } from "./providers";
import Sidebar from "./components/sidebar";
import Footer from "./components/Footer";
import SidebarWrapper from "./components/SidebarWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "FiveM dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  return (
    <html lang="en" className="scroll-smooth">
      <body>
        <Providers>
          <div className="fixed top-0 z-40 w-full">
            <Navbar />
            {/* <SidebarWrapper /> */}
          </div>
          <main className="pt-16">{children}</main>
          <section className="z-50">
            <Footer />
          </section>
        </Providers>
      </body>
    </html>
  );
}
