
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import NavbarAdmin from "./components/dashboard/Navbar-admin";
import { Providers } from "./providers";
import Footer from "./components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "FiveM dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  return (
    <html lang="en" className="scroll-smooth" suppressHydrationWarning>
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
            (function(){
              try {
                var stored = localStorage.getItem('theme');
                var theme = stored === 'dark' || stored === 'light' ? stored : (window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light');
                var root = document.documentElement;
                root.classList.remove('light','dark');
                root.classList.add(theme);
              } catch (e) {}
            })();
          `,
          }}
        />
      </head>
      <body>
        <Providers>
          <div className="fixed top-0 z-40 w-full">
            <Navbar />
            <NavbarAdmin />
          </div>
          <main className="pt-16">{children}</main>
          <section className="z-50">
            <Footer />
          </section>
        </Providers>
      </body>
    </html>
  );
}
